apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::175450128680:role/eksctl-eksctl-demo1-nodegroup-ng-NodeInstanceRole-R9RIV26L0OYP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::175450128680:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-23T19:59:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1543"
  uid: abb6ad31-9358-4703-80e5-454c030c48e4
